version: "3.9"

services:
  database:
    container_name: postgres
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
